"""add im command response payload

Revision ID: 9da7ce1cd74a
Revises: 72d48703ca92
Create Date: 2026-09-05 02:54:35.173890

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9da7ce1cd74a"
down_revision: str | Sequence[str] | None = "72d48703ca92"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("im_webhook_receipts", sa.Column("response_payload", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("im_webhook_receipts", "response_payload")
    # ### end Alembic commands ###
