"""add im link access requests

Revision ID: a20bbb53ccff
Revises: 9da7ce1cd74a
Create Date: 2026-09-07 06:40:22.690759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by sqlmodel.sql.sqltypes.AutoString in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = 'a20bbb53ccff'
down_revision: Union[str, Sequence[str], None] = '9da7ce1cd74a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('im_link_access_requests',
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('im_user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('chat_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['im_connector_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_im_link_access_request_user', 'im_link_access_requests', ['user_id'], unique=False)
    op.create_index('ix_im_link_access_request_workspace_status', 'im_link_access_requests', ['workspace_id', 'status'], unique=False)
    op.create_index(op.f('ix_im_link_access_requests_account_id'), 'im_link_access_requests', ['account_id'], unique=False)
    op.create_index(op.f('ix_im_link_access_requests_org_id'), 'im_link_access_requests', ['org_id'], unique=False)
    op.create_index(op.f('ix_im_link_access_requests_workspace_id'), 'im_link_access_requests', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_im_link_access_requests_workspace_id'), table_name='im_link_access_requests')
    op.drop_index(op.f('ix_im_link_access_requests_org_id'), table_name='im_link_access_requests')
    op.drop_index(op.f('ix_im_link_access_requests_account_id'), table_name='im_link_access_requests')
    op.drop_index('ix_im_link_access_request_workspace_status', table_name='im_link_access_requests')
    op.drop_index('ix_im_link_access_request_user', table_name='im_link_access_requests')
    op.drop_table('im_link_access_requests')
    # ### end Alembic commands ###
